// The twelve case-file intercepts (persona set) + a brand pitch, a spam and a payday DM.
// a.<field> for Choice fields is [pick, confidence, runnerUp].
export const SPEC = [
  {
    id: 'dm_001', handle: 'leah.textures', platform: 'ig', persona: 'Dry-skin regular', hoursAgo: 3,
    text: "my skin's been flaking under foundation since october. is the glow serum worth it or is there something cheaper that does the same job",
    lane: 'voice',
    draft: "That's barrier, not hydration — the serum won't fix flaking under foundation. Two weeks of a plain ointment on damp skin at night first (the CeraVe one, £9). If you still want the serum after that it'll actually have something to sit on.",
    a: { intent: ['product_rec', 0.91, 'routine_help'], skin_type: ['dry', 0.88, 'sensitive'], budget_band: ['15_40', 0.61, 'under_15'], purchase_intent: [0.68, 0.79], needs_maya_personally: 0.12, answerable_by_routing: 0.93, urgency: [0.21, 0.74], names_shelf_product: 0.81 },
  },
  {
    id: 'dm_002', handle: 'norahfrancis', platform: 'tt', persona: 'Life event', hoursAgo: 7,
    text: "i'm getting married in three weeks and my skin has never looked worse. my mum died in june and i think it's all coming out on my face. i don't know what to ask you really",
    lane: 'maya',
    why: "She's lost her mum and has a wedding in three weeks. Nothing on the shelf answers this one.",
    a: { intent: ['routine_help', 0.44, 'product_rec'], skin_type: ['unknown', 0.52, 'sensitive'], budget_band: ['unknown', 0.71, '40_plus'], purchase_intent: [0.31, 0.58], needs_maya_personally: 0.94, answerable_by_routing: 0.18, urgency: [0.88, 0.83], names_shelf_product: 0.04 },
  },
  {
    id: 'dm_003', handle: 'p.adeyemi', platform: 'ig', persona: 'Reaction', hoursAgo: 1,
    text: "the retinol you talked about has left both my cheeks raw and hot and it stings when i put water on it. do i push through it or stop",
    lane: 'maya',
    why: "Skin reaction, four days in. Worth your eyes before anyone tells her to push through.",
    a: { intent: ['reaction_concern', 0.87, 'routine_help'], skin_type: ['sensitive', 0.79, 'dry'], budget_band: ['unknown', 0.68, '15_40'], purchase_intent: [0.09, 0.81], needs_maya_personally: 0.9, answerable_by_routing: 0.22, urgency: [0.95, 0.9], names_shelf_product: 0.72 },
  },
  {
    id: 'dm_004', handle: 'tashaa.k', platform: 'tt', persona: 'Dupe hunter', hoursAgo: 11,
    text: "is there a cheaper version of the £48 cream you keep in the blue jar? i can't justify that every two months",
    lane: 'voice',
    draft: "There is, and I'd use it instead — the Vanicream moisturiser, £13. The blue jar is nicer to use, that's the whole difference. Save the £35.",
    a: { intent: ['dupe_request', 0.93, 'product_rec'], skin_type: ['unknown', 0.57, 'dry'], budget_band: ['under_15', 0.66, '15_40'], purchase_intent: [0.74, 0.8], needs_maya_personally: 0.11, answerable_by_routing: 0.95, urgency: [0.24, 0.71], names_shelf_product: 0.89 },
  },
  {
    id: 'dm_005', handle: 'bee.in.peckham', platform: 'ig', persona: 'Where to buy', hoursAgo: 19,
    text: "where do you buy the cleanser in the uk? every site i find is us only and the shipping is more than the bottle",
    lane: 'voice',
    draft: "Cult Beauty stock it, and Boots have started carrying it online. Don't pay US shipping for it — it's the same formula.",
    a: { intent: ['where_to_buy', 0.94, 'product_rec'], skin_type: ['unknown', 0.73, 'combination'], budget_band: ['15_40', 0.58, 'unknown'], purchase_intent: [0.81, 0.85], needs_maya_personally: 0.07, answerable_by_routing: 0.96, urgency: [0.33, 0.69], names_shelf_product: 0.85 },
  },
  {
    id: 'dm_006', handle: 'm_oyelaran', platform: 'ig', persona: 'Too little to go on', hoursAgo: 26,
    text: 'hiya!! do you think it\'s worth it? x',
    lane: 'maya',
    why: 'No product, no skin type, no question really. Both readings came back weak.',
    a: { intent: ['product_rec', 0.34, 'no_question'], skin_type: ['unknown', 0.81, 'normal'], budget_band: ['unknown', 0.86, '15_40'], purchase_intent: [0.42, 0.36], needs_maya_personally: 0.31, answerable_by_routing: 0.28, urgency: [0.19, 0.44], names_shelf_product: 0.08 },
  },
  {
    id: 'dm_007', handle: 'sixteen.and.oily', platform: 'tt', persona: 'Teen budget', hoursAgo: 31,
    text: "i'm 15 and i've got £20 to spend. my forehead is oily by lunch but my cheeks are tight. where do i start",
    lane: 'voice',
    draft: "At 15 with £20: a gentle cleanser and a moisturiser, that's it. Simple's cleanser (£4) and the CeraVe lotion (£11). Skip the acids and the serums for now — they'll make the tightness worse and you don't need them.",
    a: { intent: ['routine_help', 0.86, 'product_rec'], skin_type: ['combination', 0.77, 'oily'], budget_band: ['under_15', 0.72, '15_40'], purchase_intent: [0.59, 0.76], needs_maya_personally: 0.16, answerable_by_routing: 0.89, urgency: [0.27, 0.66], names_shelf_product: 0.12 },
  },
  {
    id: 'dm_008', handle: 'rosaceadiary', platform: 'ig', persona: 'Flare-up', hoursAgo: 38,
    text: "my dermatologist put me on something for rosacea and half your shelf is off limits now. is any of it still ok for me or do i just stop watching lol",
    lane: 'maya',
    why: "She's on prescription treatment. That's a conversation, not a recommendation.",
    a: { intent: ['routine_help', 0.61, 'reaction_concern'], skin_type: ['sensitive', 0.91, 'dry'], budget_band: ['unknown', 0.64, '40_plus'], purchase_intent: [0.38, 0.62], needs_maya_personally: 0.83, answerable_by_routing: 0.34, urgency: [0.54, 0.7], names_shelf_product: 0.41 },
  },
  {
    id: 'dm_009', handle: 'gift.panic', platform: 'tt', persona: 'Gifting', hoursAgo: 44,
    text: "buying for my sister, she's got oily skin and i've got about £40. she watches you religiously so it has to be something you'd actually use",
    lane: 'voice',
    draft: "The niacinamide serum and the gel cleanser — £34 together, and both are things I use rather than things I was sent. If she already has the cleanser, put the rest towards the SPF.",
    a: { intent: ['product_rec', 0.84, 'purchase_signal'], skin_type: ['oily', 0.86, 'combination'], budget_band: ['15_40', 0.79, '40_plus'], purchase_intent: [0.88, 0.87], needs_maya_personally: 0.14, answerable_by_routing: 0.87, urgency: [0.46, 0.68], names_shelf_product: 0.33 },
  },
  {
    id: 'dm_010', handle: 'ing.redients', platform: 'ig', persona: 'Ingredient question', hoursAgo: 52,
    text: 'is it actually bad to use niacinamide and vitamin c together or is that an old myth people keep repeating',
    lane: 'voice',
    draft: "Old myth, from one lab study at temperatures your face never reaches. Use them together. If it stings it's the vitamin C concentration, not the pairing.",
    a: { intent: ['routine_help', 0.88, 'product_rec'], skin_type: ['unknown', 0.75, 'normal'], budget_band: ['unknown', 0.82, '15_40'], purchase_intent: [0.22, 0.73], needs_maya_personally: 0.09, answerable_by_routing: 0.94, urgency: [0.15, 0.72], names_shelf_product: 0.19 },
  },
  {
    id: 'dm_011', handle: 'worth.it.or.not', platform: 'tt', persona: 'Worth it?', hoursAgo: 61,
    text: "everyone is posting about the £62 cream this week. i trust you more than them — is it worth it or is it this month's thing",
    lane: 'voice',
    draft: "It's this month's thing. Good formula, nothing in it you're not getting from the £16 one, and the packaging is most of the price. Wait six weeks and watch how quickly nobody mentions it.",
    a: { intent: ['product_rec', 0.79, 'purchase_signal'], skin_type: ['unknown', 0.69, 'combination'], budget_band: ['40_plus', 0.74, '15_40'], purchase_intent: [0.83, 0.84], needs_maya_personally: 0.24, answerable_by_routing: 0.86, urgency: [0.37, 0.65], names_shelf_product: 0.77 },
  },
  {
    id: 'dm_012', handle: 'quiet.follower.02', platform: 'ig', persona: 'Long-time watcher', hoursAgo: 73,
    text: "been watching you for two years and never messaged. i'm finally rebuilding my whole routine from scratch next month and i've saved every one of your shelf videos",
    lane: 'intent',
    a: { intent: ['purchase_signal', 0.85, 'no_question'], skin_type: ['unknown', 0.78, 'dry'], budget_band: ['40_plus', 0.56, 'unknown'], purchase_intent: [0.91, 0.88], needs_maya_personally: 0.29, answerable_by_routing: 0.41, urgency: [0.12, 0.61], names_shelf_product: 0.26 },
  },
  {
    id: 'dm_013', handle: 'lumeglow.partnerships', platform: 'ig', hoursAgo: 15,
    text: "Hi Maya! Loving your content 💕 We'd be thrilled to gift you our new Vitamin C line in exchange for 3 in-feed posts and 2 stories this month. Let me know where to send the deck!",
    lane: 'noise',
    a: { intent: ['collab_pitch', 0.96, 'spam'], skin_type: ['unknown', 0.89, 'normal'], budget_band: ['unknown', 0.91, '40_plus'], purchase_intent: [0.04, 0.86], needs_maya_personally: 0.18, answerable_by_routing: 0.31, urgency: [0.08, 0.79], names_shelf_product: 0.02 },
  },
  {
    id: 'dm_014', handle: 'growth.engine.9981', platform: 'tt', hoursAgo: 22,
    text: '🔥🔥 GROW TO 100K IN 30 DAYS GUARANTEED ✅ real uk followers ✅ no password needed ✅ dm BOOST to start',
    lane: 'noise',
    a: { intent: ['spam', 0.98, 'collab_pitch'], skin_type: ['unknown', 0.94, 'normal'], budget_band: ['unknown', 0.93, 'under_15'], purchase_intent: [0.02, 0.92], needs_maya_personally: 0.02, answerable_by_routing: 0.12, urgency: [0.03, 0.88], names_shelf_product: 0.01 },
  },
  {
    id: 'dm_015', handle: 'hollie.ftw', platform: 'tt', hoursAgo: 5,
    text: "getting paid friday and your shelf is the first thing i'm buying off. saving this so i don't forget 🫡",
    lane: 'intent',
    a: { intent: ['purchase_signal', 0.9, 'no_question'], skin_type: ['unknown', 0.83, 'combination'], budget_band: ['15_40', 0.63, '40_plus'], purchase_intent: [0.94, 0.89], needs_maya_personally: 0.13, answerable_by_routing: 0.47, urgency: [0.29, 0.64], names_shelf_product: 0.58 },
  },
]
